### ISSUE TITLE
XNIO and Remoting only (2)

### ISSUE THREAD

**Issue by kabir** [kabir/maven-snapshot-ci#14]
```
name: XNIO and Remoting
env:
  MAVEN_OPTS: -Xms756M -Xmx1g
components:
  - name: xnio
    org: kabir
    branch: '3.8'
    mavenOpts: -DskipTests
  - name: jboss-remoting
    org: kabir
    branch: '5.0'
    mavenOpts: -DskipTests
    dependencies:
      - name: xnio
        property: xnio.version
```
