### ISSUE TITLE
Remoting into full

### ISSUE THREAD

**Issue by yersan** [kabir/maven-snapshot-ci#18]
```
name: Remoting in full
env:
  MAVEN_OPTS: '-Xms756M -Xmx1g'
components:
  - name: jboss-remoting
    org: yersan
    branch: REM3-371
    mavenOpts: '-DskipTests'
  - name: wildfly-core
    org: yersan
    branch: gh-action-fixes
    dependencies:
      - name: jboss-remoting
        property: version.org.jboss.remoting
  - name: wildfly
    org: yersan
    branch: gh-action-fixes
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
